window.PORTAL = {
 "series": [
  {
   "id": "pureday",
   "title": "조아름의 퓨어데이",
   "titleNote": "가제",
   "genre": "현대 일상 판타지 · 펜+수채 웹툰",
   "logline": "서울에서 펜과 수채로 하루를 그리는 스물네 살 조아름. 아버지가 만든 AR 글래스의 '버그' 덕분에, 동생 하임과 함께 보통 사람 눈에 보이지 않던 영적 전쟁을 보게 된다.",
   "status": "시즌1 프롤로그 + 5화 공개",
   "cover": "assets/pureday/cover.jpg",
   "episodes": [
    {
     "num": 0,
     "label": "프롤로그",
     "title": "비 오는 밤의 코드",
     "summary": "서울에서 펜과 수채로 하루를 그리는 조아름의 평범한 하루. 저녁에 아버지의 연구실(소울 아이즈 랩스)에 도시락을 들고 들렀다가, 천둥 치는 밤 모니터에 쏟아지는 알 수 없는 코드와 오류가 풀리는 순간을 함께 본다. 번개 빛에 비친 유리창에 잠깐 어린양의 실루엣이 스치고, 아름은 그것을 스케치북에 그려 둔다.",
     "scenes": 30,
     "pages": [
      "assets/pureday/ep0/001.jpg",
      "assets/pureday/ep0/002.jpg",
      "assets/pureday/ep0/003.jpg",
      "assets/pureday/ep0/004.jpg",
      "assets/pureday/ep0/005.jpg",
      "assets/pureday/ep0/006.jpg",
      "assets/pureday/ep0/007.jpg",
      "assets/pureday/ep0/008.jpg",
      "assets/pureday/ep0/009.jpg",
      "assets/pureday/ep0/010.jpg",
      "assets/pureday/ep0/011.jpg",
      "assets/pureday/ep0/012.jpg",
      "assets/pureday/ep0/013.jpg",
      "assets/pureday/ep0/014.jpg",
      "assets/pureday/ep0/015.jpg",
      "assets/pureday/ep0/016.jpg",
      "assets/pureday/ep0/017.jpg",
      "assets/pureday/ep0/018.jpg",
      "assets/pureday/ep0/019.jpg",
      "assets/pureday/ep0/020.jpg",
      "assets/pureday/ep0/021.jpg",
      "assets/pureday/ep0/022.jpg",
      "assets/pureday/ep0/023.jpg",
      "assets/pureday/ep0/024.jpg",
      "assets/pureday/ep0/025.jpg",
      "assets/pureday/ep0/026.jpg",
      "assets/pureday/ep0/027.jpg",
      "assets/pureday/ep0/028.jpg"
     ],
     "thumb": "assets/pureday/thumb0.jpg"
    },
    {
     "num": 1,
     "label": "1화",
     "title": "초원의 별",
     "summary": "가족이 몽골 단기선교를 떠난다. 아름은 'Pureday' 라이브 방송을, 하임은 아버지 회사의 베타 글래스(하이퍼 글래스 v04)와 드론을 연동한다. 테를지 외곽의 밤, 은하수 아래 소리 없는 마른번개가 치자 하임의 글래스에만 코드가 쏟아지고 초원 위로 금빛 경계선이 겹친다. 빛의 중심에서 어린양 타미가 나타나 남매를 기암괴석 지대로 이끌고, 검독수리 아퀼라가 내려앉고, 앵무새 페이가 \"퓨어랜드의 보호막이 깨졌어요\"라고 통역한다. 끝에 하임이 글래스를 아름에게 씌워 주고, 아름도 하늘을 가르는 금빛 성벽의 금 간 자국을 본다.",
     "scenes": 40,
     "pages": [
      "assets/pureday/ep1/001.jpg",
      "assets/pureday/ep1/002.jpg",
      "assets/pureday/ep1/003.jpg",
      "assets/pureday/ep1/004.jpg",
      "assets/pureday/ep1/005.jpg",
      "assets/pureday/ep1/006.jpg",
      "assets/pureday/ep1/007.jpg",
      "assets/pureday/ep1/008.jpg",
      "assets/pureday/ep1/009.jpg",
      "assets/pureday/ep1/010.jpg",
      "assets/pureday/ep1/011.jpg",
      "assets/pureday/ep1/012.jpg",
      "assets/pureday/ep1/013.jpg",
      "assets/pureday/ep1/014.jpg",
      "assets/pureday/ep1/015.jpg",
      "assets/pureday/ep1/016.jpg",
      "assets/pureday/ep1/017.jpg",
      "assets/pureday/ep1/018.jpg",
      "assets/pureday/ep1/019.jpg",
      "assets/pureday/ep1/020.jpg",
      "assets/pureday/ep1/021.jpg",
      "assets/pureday/ep1/022.jpg",
      "assets/pureday/ep1/023.jpg",
      "assets/pureday/ep1/024.jpg",
      "assets/pureday/ep1/025.jpg",
      "assets/pureday/ep1/026.jpg",
      "assets/pureday/ep1/027.jpg",
      "assets/pureday/ep1/028.jpg",
      "assets/pureday/ep1/029.jpg",
      "assets/pureday/ep1/030.jpg",
      "assets/pureday/ep1/031.jpg",
      "assets/pureday/ep1/032.jpg",
      "assets/pureday/ep1/033.jpg",
      "assets/pureday/ep1/034.jpg",
      "assets/pureday/ep1/035.jpg",
      "assets/pureday/ep1/036.jpg",
      "assets/pureday/ep1/037.jpg",
      "assets/pureday/ep1/038.jpg"
     ],
     "thumb": "assets/pureday/ep1/001.jpg"
    },
    {
     "num": 2,
     "label": "2화",
     "title": "보이는 것과 보이지 않는 것",
     "summary": "새벽, 게르로 돌아온 남매를 아버지가 기다리고 있다. 아버지는 비 오는 밤의 코드 이야기를 털어놓고 열왕기하 6:17을 읽어 준다. 다음 날 울란바토르 시장에서 글래스를 써 보니 사람들 그림자 끝에 작은 마물들(무심·탐심·낙심)이 붙어 있다. 하임은 \"이거 방송하면 대박\"이라며 들뜨지만, 아름은 사람을 콘텐츠로 쓰지 않는다며 멈춘다. 길 잃은 아이를 아름이 도와 엄마를 찾아 주자, 글래스 속 그림자 하나가 연기처럼 흩어진다. 그날 밤 타미가 게르 문 앞에 와 있고, 페이가 전한다. \"내일 새벽, 따라오래요.\"",
     "scenes": 38,
     "pages": [
      "assets/pureday/ep2/001.jpg",
      "assets/pureday/ep2/002.jpg",
      "assets/pureday/ep2/003.jpg",
      "assets/pureday/ep2/004.jpg",
      "assets/pureday/ep2/005.jpg",
      "assets/pureday/ep2/006.jpg",
      "assets/pureday/ep2/007.jpg",
      "assets/pureday/ep2/008.jpg",
      "assets/pureday/ep2/009.jpg",
      "assets/pureday/ep2/010.jpg",
      "assets/pureday/ep2/011.jpg",
      "assets/pureday/ep2/012.jpg",
      "assets/pureday/ep2/013.jpg",
      "assets/pureday/ep2/014.jpg",
      "assets/pureday/ep2/015.jpg",
      "assets/pureday/ep2/016.jpg",
      "assets/pureday/ep2/017.jpg",
      "assets/pureday/ep2/018.jpg",
      "assets/pureday/ep2/019.jpg",
      "assets/pureday/ep2/020.jpg",
      "assets/pureday/ep2/021.jpg",
      "assets/pureday/ep2/022.jpg",
      "assets/pureday/ep2/023.jpg",
      "assets/pureday/ep2/024.jpg",
      "assets/pureday/ep2/025.jpg",
      "assets/pureday/ep2/026.jpg",
      "assets/pureday/ep2/027.jpg",
      "assets/pureday/ep2/028.jpg",
      "assets/pureday/ep2/029.jpg",
      "assets/pureday/ep2/030.jpg",
      "assets/pureday/ep2/031.jpg",
      "assets/pureday/ep2/032.jpg",
      "assets/pureday/ep2/033.jpg",
      "assets/pureday/ep2/034.jpg",
      "assets/pureday/ep2/035.jpg",
      "assets/pureday/ep2/036.jpg"
     ],
     "thumb": "assets/pureday/ep2/001.jpg"
    },
    {
     "num": 3,
     "label": "3화",
     "title": "보호막이 깨진 날",
     "summary": "새벽, 타미와 페이를 따라 기암괴석 사이 빛의 틈을 지난 남매가 처음 퓨어랜드에 선다. 옷은 평상복 그대로(갑주 0단계). 금빛 성, 하늘을 덮던 보호막의 깨진 조각들, 검게 그을린 들판 — 드래곤 군대의 흔적. 흰 사슴 케렌이 걷는 자리마다 독기가 맑아진다. 그을린 마을 담 뒤에 숨은 퓨어랜드 아이에게 아름이 \"나도 무서워\"라고 솔직하게 말하고 손을 잡자, 허리에 가는 빛의 띠(진리의 허리띠, 1단계)가 생긴다. 먼 산 너머로 거대한 날개 그림자가 지나가고, 성벽의 금이 한 줄 더 간다. 아름은 펜을 쥔다 — \"그려서 알려야 해.\"",
     "scenes": 40,
     "pages": [
      "assets/pureday/ep3/001.jpg",
      "assets/pureday/ep3/002.jpg",
      "assets/pureday/ep3/003.jpg",
      "assets/pureday/ep3/004.jpg",
      "assets/pureday/ep3/005.jpg",
      "assets/pureday/ep3/006.jpg",
      "assets/pureday/ep3/007.jpg",
      "assets/pureday/ep3/008.jpg",
      "assets/pureday/ep3/009.jpg",
      "assets/pureday/ep3/010.jpg",
      "assets/pureday/ep3/011.jpg",
      "assets/pureday/ep3/012.jpg",
      "assets/pureday/ep3/013.jpg",
      "assets/pureday/ep3/014.jpg",
      "assets/pureday/ep3/015.jpg",
      "assets/pureday/ep3/016.jpg",
      "assets/pureday/ep3/017.jpg",
      "assets/pureday/ep3/018.jpg",
      "assets/pureday/ep3/019.jpg",
      "assets/pureday/ep3/020.jpg",
      "assets/pureday/ep3/021.jpg",
      "assets/pureday/ep3/022.jpg",
      "assets/pureday/ep3/023.jpg",
      "assets/pureday/ep3/024.jpg",
      "assets/pureday/ep3/025.jpg",
      "assets/pureday/ep3/026.jpg",
      "assets/pureday/ep3/027.jpg",
      "assets/pureday/ep3/028.jpg",
      "assets/pureday/ep3/029.jpg",
      "assets/pureday/ep3/030.jpg",
      "assets/pureday/ep3/031.jpg",
      "assets/pureday/ep3/032.jpg",
      "assets/pureday/ep3/033.jpg",
      "assets/pureday/ep3/034.jpg",
      "assets/pureday/ep3/035.jpg",
      "assets/pureday/ep3/036.jpg",
      "assets/pureday/ep3/037.jpg"
     ],
     "thumb": "assets/pureday/ep3/001.jpg"
    },
    {
     "num": 4,
     "label": "4화",
     "title": "첫 마물",
     "summary": "날개 그림자를 본 남매가 빛의 틈을 지나 몽골로 돌아온다. 게르에서 밤새 기다린 **조성민 박사**는 글래스 데이터에서 퓨어랜드의 보호막 에너지가 꺼져 가는 것을 보고 있다. 그런데 하임에게는 비밀이 있다 — 2화 시장에서 글래스로 찍은 사람들의 그림자 영상을 몰래 편집해 '영적 전쟁 실화'로 올리려 한 것. 다음 날 울란바토르 아동센터 담벼락의 금에서 **낙심의 마물**이 기어 나와 젊은 선생님의 그림자에 달라붙는다. 칠흑에 은빛 문양의 퓨마 **은바**가 지붕에서 뛰어내려 선봉을 친다(보통 사람에겐 큰 검은 고양이). 뛰어든 하임은 경계 속으로 빨려 들어가지만 맨손으로는 마물을 이기지 못한다. 페이: \"그림자는 거짓 속에 숨어요.\" 하임이 영상을 고백하고 지우자 허리에 **진리의 허리띠**가 감기고, 장갑과 장비가 첫 중세 무기로 강화된다 — **손바닥을 덧댄 가죽 장갑 + 참나무 쿼터스태프**. 은바와 함께 마물을 연기로 흩는다. 끝: 아퀼라가 내려와 비룡대가 방송 전파를 노린다는 소식을 전한다.",
     "scenes": 40,
     "pages": [
      "assets/pureday/ep4/001.jpg",
      "assets/pureday/ep4/002.jpg",
      "assets/pureday/ep4/003.jpg",
      "assets/pureday/ep4/004.jpg",
      "assets/pureday/ep4/005.jpg",
      "assets/pureday/ep4/006.jpg",
      "assets/pureday/ep4/007.jpg",
      "assets/pureday/ep4/008.jpg",
      "assets/pureday/ep4/009.jpg",
      "assets/pureday/ep4/010.jpg",
      "assets/pureday/ep4/011.jpg",
      "assets/pureday/ep4/012.jpg",
      "assets/pureday/ep4/013.jpg",
      "assets/pureday/ep4/014.jpg",
      "assets/pureday/ep4/015.jpg",
      "assets/pureday/ep4/016.jpg",
      "assets/pureday/ep4/017.jpg",
      "assets/pureday/ep4/018.jpg",
      "assets/pureday/ep4/019.jpg",
      "assets/pureday/ep4/020.jpg",
      "assets/pureday/ep4/021.jpg",
      "assets/pureday/ep4/022.jpg",
      "assets/pureday/ep4/023.jpg",
      "assets/pureday/ep4/024.jpg",
      "assets/pureday/ep4/025.jpg",
      "assets/pureday/ep4/026.jpg",
      "assets/pureday/ep4/027.jpg",
      "assets/pureday/ep4/028.jpg",
      "assets/pureday/ep4/029.jpg",
      "assets/pureday/ep4/030.jpg",
      "assets/pureday/ep4/031.jpg",
      "assets/pureday/ep4/032.jpg",
      "assets/pureday/ep4/033.jpg",
      "assets/pureday/ep4/034.jpg",
      "assets/pureday/ep4/035.jpg",
      "assets/pureday/ep4/036.jpg",
      "assets/pureday/ep4/037.jpg"
     ],
     "thumb": "assets/pureday/ep4/001.jpg"
    },
    {
     "num": 5,
     "label": "5화",
     "title": "끊기지 않는 방송",
     "summary": "아퀼라의 경고 다음 날, 아름은 울란바토르가 내려다보이는 언덕에서 'Pureday' 라이브를 연다 — 아동센터 아이들이 그린 그림을 소개하고 도시를 스케치하는 방송. 북쪽에서 **비룡대**(날개 달린 작은 용 떼)가 몰려와 언덕의 송신탑에 잿빛 잡음을 뿜고, 방송이 끊기기 시작한다. 보통 사람 눈에는 케이블이 저절로 움직이는 것뿐 — 원숭이 **치코**가 끊긴 선을 다시 잇고 있다. 그때 구경 온 아이가 넘어져 운다. 카메라가 우는 아이를 비추자 하트가 쏟아지고, 비룡 한 마리가 아름의 귀에 속삭인다. \"계속 찍어. 다들 이런 걸 보고 싶어 해.\" 아름은 카메라를 돌리고 아이를 먼저 안는다. \"제가 방송하는 건 사람이 아니라, 부르심이에요.\" 가슴에 **의의 호심경**가 빛으로 맺히고, 장갑과 장비가 두 번째 단계로 강화된다 — **세 손가락을 덧댄 가죽 궁수 장갑 + 단궁과 작은 화살통**. 아름의 빛 화살, 아퀼라의 강하, 하임과 은바의 목봉, 치코의 마지막 연결로 비룡대가 흩어진다. 끝: 그날 밤, 조성민 박사가 오래된 노트를 펼친다(6화 예고).",
     "scenes": 40,
     "pages": [
      "assets/pureday/ep5/001.jpg",
      "assets/pureday/ep5/002.jpg",
      "assets/pureday/ep5/003.jpg",
      "assets/pureday/ep5/004.jpg",
      "assets/pureday/ep5/005.jpg",
      "assets/pureday/ep5/006.jpg",
      "assets/pureday/ep5/007.jpg",
      "assets/pureday/ep5/008.jpg",
      "assets/pureday/ep5/009.jpg",
      "assets/pureday/ep5/010.jpg",
      "assets/pureday/ep5/011.jpg",
      "assets/pureday/ep5/012.jpg",
      "assets/pureday/ep5/013.jpg",
      "assets/pureday/ep5/014.jpg",
      "assets/pureday/ep5/015.jpg",
      "assets/pureday/ep5/016.jpg",
      "assets/pureday/ep5/017.jpg",
      "assets/pureday/ep5/018.jpg",
      "assets/pureday/ep5/019.jpg",
      "assets/pureday/ep5/020.jpg",
      "assets/pureday/ep5/021.jpg",
      "assets/pureday/ep5/022.jpg",
      "assets/pureday/ep5/023.jpg",
      "assets/pureday/ep5/024.jpg",
      "assets/pureday/ep5/025.jpg",
      "assets/pureday/ep5/026.jpg",
      "assets/pureday/ep5/027.jpg",
      "assets/pureday/ep5/028.jpg",
      "assets/pureday/ep5/029.jpg",
      "assets/pureday/ep5/030.jpg",
      "assets/pureday/ep5/031.jpg",
      "assets/pureday/ep5/032.jpg",
      "assets/pureday/ep5/033.jpg",
      "assets/pureday/ep5/034.jpg",
      "assets/pureday/ep5/035.jpg",
      "assets/pureday/ep5/036.jpg"
     ],
     "thumb": "assets/pureday/ep5/001.jpg"
    }
   ]
  },
  {
   "id": "joshua",
   "title": "여호수아",
   "genre": "성경 역사 드라마 / 펜화 웹툰",
   "logline": "모세가 죽고 홀로 남은 여호수아. 넘치는 요단과 굳게 닫힌 여리고 앞에서, 약속을 믿은 사람들의 이야기.",
   "status": "시즌1 10/10화 공개",
   "url": "https://tjkim-image01.github.io/Joshua-story/",
   "cover": "assets/joshua/ep1.jpg",
   "episodes": [
    {
     "num": 1,
     "label": "1화",
     "title": "강하고 담대하라",
     "summary": "무너지는 여리고성을 먼저 보여준 뒤 모세가 죽은 모압 평지로 돌아간다. 홀로 남은 여호수아가 흔들리다 부르심을 받고, 요단을 건널 준비를 명령하고, 동편 지파들의 충성 맹세를 받는다. 두 정탐꾼이 여리고에 잠입해 라합의 집에 숨고, 왕의 병사들이 문을 두드리며 끝난다.",
     "coord": "성경: 여호수아 1:1–2:3 · 70장면",
     "thumb": "assets/joshua/ep1.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=1",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=1"
    },
    {
     "num": 2,
     "label": "2화",
     "title": "붉은 줄",
     "summary": "라합이 왕의 병사들을 속여 돌려보내고, 지붕 위에서 여호와를 고백하며 가족의 생명을 맹세받는다. 붉은 줄을 타고 성벽을 내려간 정탐꾼들은 사흘간 산에 숨었다가 여호수아에게 돌아가 보고한다. 성문을 걸어 잠근 여리고 안에서 라합이 붉은 줄을 쥐고 동쪽을 바라보며 끝난다.",
     "coord": "성경: 여호수아 2:3–24 · 70장면",
     "thumb": "assets/joshua/ep2.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=2",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=2"
    },
    {
     "num": 3,
     "label": "3화",
     "title": "물이 멈춘 날",
     "summary": "넘치는 요단 앞에 선 백성에게 여호수아가 성결을 명령한다. 법궤를 멘 제사장들의 발이 물에 닿자 상류에서 물이 쌓여 서고, 온 백성이 마른 땅으로 건넌다. 마지막으로 제사장들이 올라오는 순간 강물이 되돌아오고, 돌아갈 길은 사라진다.",
     "coord": "성경: 여호수아 3장, 4:15–18 · 70장면",
     "thumb": "assets/joshua/ep3.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=3",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=3"
    },
    {
     "num": 4,
     "label": "4화",
     "title": "열두 돌",
     "summary": "먼 훗날 한 소년이 길갈의 선돌을 묻는 장면으로 시작해, 물이 멈춘 그날 강 한가운데서 열두 사람이 돌을 메고 나온 이야기로 돌아간다. 길갈에 열두 돌을 세우고 백성은 여호수아를 두려워한다. 소식을 들은 가나안 왕들의 마음이 녹고, 여호수아는 싸움보다 먼저 언약의 표를 명령받는다.",
     "coord": "성경: 여호수아 4:1–5:2 · 70장면",
     "thumb": "assets/joshua/ep4.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=4",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=4"
    },
    {
     "num": 5,
     "label": "5화",
     "title": "신을 벗으라",
     "summary": "여리고 앞 들판에서 칼 든 사람과 마주친 여호수아로 시작해, 열흘 전 길갈의 할례와 유월절, 만나가 그친 아침으로 돌아간다. 다시 그날 밤, 칼 든 사람은 여호와의 군대 대장이었고 여호수아는 신을 벗는다. 여리고를 도는 기이한 전략을 받고 맨발로 진영에 돌아가며 끝난다.",
     "coord": "성경: 여호수아 5:2–6:5 · 70장면",
     "thumb": "assets/joshua/ep5.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=5",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=5"
    },
    {
     "num": 6,
     "label": "6화",
     "title": "일곱째 날",
     "summary": "말없이 성을 도는 첫째 날로 시작해, 조롱과 두려움이 쌓이는 여섯 날을 지난다. 일곱째 날 일곱 바퀴 뒤 나팔과 함성에 여리고 성벽이 무너지고, 정탐꾼들이 맹세대로 라합의 가족을 구해 낸다. 폐허에서 금을 몰래 품는 한 사내(아간)의 눈으로 끝난다.",
     "coord": "성경: 여호수아 6장 · 70장면",
     "thumb": "assets/joshua/ep6.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=6",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=6"
    },
    {
     "num": 7,
     "label": "7화",
     "title": "아이성의 패배",
     "summary": "작은 성 아이 앞에서 도망치는 이스라엘로 시작해, 기도 없이 삼천 명만 보낸 교만의 과정으로 돌아간다. 서른여섯 명이 죽고 백성의 마음이 녹는다. 옷을 찢고 엎드린 여호수아에게 여호와께서 진영 안의 죄를 알리시고, 잠 못 드는 아간의 천막을 지나 제비가 유다 지파에 떨어지며 끝난다.",
     "coord": "성경: 여호수아 7:1–16 · 70장면",
     "thumb": "assets/joshua/ep7.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=7",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=7"
    },
    {
     "num": 8,
     "label": "8화",
     "title": "아골 골짜기",
     "summary": "아골 골짜기의 돌무더기 앞에 선 여호수아로 시작해, 그날 아침 제비가 족속과 가문을 좁혀 아간에게 떨어지는 과정으로 돌아간다. 아간이 자복하고 천막 땅속에서 외투와 은금이 나온다. 골짜기의 심판 뒤 진노가 그치고, 다시 두려워하지 말라는 말씀과 함께 여호수아가 아이로 올라갈 채비를 하며 끝난다.",
     "coord": "성경: 여호수아 7:16–8:2 · 70장면",
     "thumb": "assets/joshua/ep8.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=8",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=8"
    },
    {
     "num": 9,
     "label": "9화",
     "title": "단창을 들라",
     "summary": "산등성이에서 단창을 든 여호수아와 불타는 아이 성으로 시작해, 사흘 전의 복병 작전으로 돌아간다. 거짓 패주로 성을 비우게 한 뒤 단창 신호에 복병이 성을 점령하고, 앞뒤로 포위된 아이 군대가 무너진다. 에발산에 제단을 쌓고 율법을 낭독하는 사이, 가나안 왕들이 동맹을 맺고 기브온 사람이 다른 길을 꾸미며 끝난다.",
     "coord": "성경: 여호수아 8:1–9:3 · 70장면",
     "thumb": "assets/joshua/ep9.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=9",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=9"
    },
    {
     "num": 10,
     "label": "10화",
     "title": "해어진 신발",
     "summary": "해어진 신발과 곰팡이 핀 떡을 들고 길갈에 나타난 사신들로 시작해, 기브온 원로들의 속임수 준비로 돌아간다. 여호와께 묻지 않은 채 조약을 맺은 이스라엘은 사흘 뒤 그들이 이웃임을 알게 되지만, 맹세 때문에 해하지 못하고 나무 패고 물 긷는 자로 삼는다. 기브온의 배신에 분노한 예루살렘 왕과 아모리 다섯 왕이 기브온을 포위하며 시즌이 끝난다.",
     "coord": "성경: 여호수아 9:3–10:5 · 70장면",
     "thumb": "assets/joshua/ep10.jpg",
     "mobile": "https://tjkim-image01.github.io/Joshua-story/mobile_viewer.html?ep=10",
     "pc": "https://tjkim-image01.github.io/Joshua-story/pc_viewer.html?ep=10"
    }
   ]
  }
 ]
};
